name: "✨ 기업 기술 블로그 탐구 일지"
description: "어떤 기업 기술 블로그를 분석했나요?"
labels: ["✨ 기업 기술 블로그 탐구 일지"]
body:
  - type: textarea
    id: description
    attributes:
      label: "📄 Describe"
      description: "새로운 개발에 대한 설명을 작성해 주세요."
      placeholder: "자세히 적을수록 좋습니다!"
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: "✅ Tasks"
      description: "해야 하는 일에 대한 Tasks를 작성해 주세요."
      placeholder: "최대한 세분화 해서 적어주세요!"
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: "🙋🏻 More"
      description: "더 하고 싶은 말이 있다면 작성해 주세요."
    validations:
      required: false
